version: 2
jobs:
  build:
    docker:
      - image: mhart/alpine-node:9.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: node --harmony ./node_modules/.bin/jest
